/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppVatRouteImport } from './routes/_app/vat'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppCategoriesRouteImport } from './routes/_app/categories'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppStandUpsIndexRouteImport } from './routes/_app/stand-ups/index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppEmployeesIndexRouteImport } from './routes/_app/employees/index'
import { Route as AppCoreMembersIndexRouteImport } from './routes/_app/core-members/index'
import { Route as AppClientsIndexRouteImport } from './routes/_app/clients/index'
import { Route as AppStandUpsIdRouteImport } from './routes/_app/stand-ups/$id'
import { Route as AppProjectsIdRouteImport } from './routes/_app/projects/$id'
import { Route as AppEmployeesIdRouteImport } from './routes/_app/employees/$id'
import { Route as AppCoreMembersIdRouteImport } from './routes/_app/core-members/$id'
import { Route as AppClientsIdRouteImport } from './routes/_app/clients/$id'
import { Route as AppProjectsIdEditRouteImport } from './routes/_app/projects/$id_.edit'
import { Route as AppEmployeesIdEditRouteImport } from './routes/_app/employees/$id_.edit'
import { Route as AppCoreMembersIdEditRouteImport } from './routes/_app/core-members/$id_.edit'
import { Route as AppClientsIdEditRouteImport } from './routes/_app/clients/$id_.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVatRoute = AppVatRouteImport.update({
  id: '/vat',
  path: '/vat',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppStandUpsIndexRoute = AppStandUpsIndexRouteImport.update({
  id: '/stand-ups/',
  path: '/stand-ups/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesIndexRoute = AppEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => AppRoute,
} as any)
const AppCoreMembersIndexRoute = AppCoreMembersIndexRouteImport.update({
  id: '/core-members/',
  path: '/core-members/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AppRoute,
} as any)
const AppStandUpsIdRoute = AppStandUpsIdRouteImport.update({
  id: '/stand-ups/$id',
  path: '/stand-ups/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdRoute = AppProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesIdRoute = AppEmployeesIdRouteImport.update({
  id: '/employees/$id',
  path: '/employees/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCoreMembersIdRoute = AppCoreMembersIdRouteImport.update({
  id: '/core-members/$id',
  path: '/core-members/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIdRoute = AppClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIdEditRoute = AppProjectsIdEditRouteImport.update({
  id: '/projects/$id_/edit',
  path: '/projects/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesIdEditRoute = AppEmployeesIdEditRouteImport.update({
  id: '/employees/$id_/edit',
  path: '/employees/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppCoreMembersIdEditRoute = AppCoreMembersIdEditRouteImport.update({
  id: '/core-members/$id_/edit',
  path: '/core-members/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsIdEditRoute = AppClientsIdEditRouteImport.update({
  id: '/clients/$id_/edit',
  path: '/clients/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AppAuditRoute
  '/categories': typeof AppCategoriesRoute
  '/settings': typeof AppSettingsRoute
  '/vat': typeof AppVatRoute
  '/clients/$id': typeof AppClientsIdRoute
  '/core-members/$id': typeof AppCoreMembersIdRoute
  '/employees/$id': typeof AppEmployeesIdRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/stand-ups/$id': typeof AppStandUpsIdRoute
  '/clients/': typeof AppClientsIndexRoute
  '/core-members/': typeof AppCoreMembersIndexRoute
  '/employees/': typeof AppEmployeesIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/stand-ups/': typeof AppStandUpsIndexRoute
  '/clients/$id/edit': typeof AppClientsIdEditRoute
  '/core-members/$id/edit': typeof AppCoreMembersIdEditRoute
  '/employees/$id/edit': typeof AppEmployeesIdEditRoute
  '/projects/$id/edit': typeof AppProjectsIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/audit': typeof AppAuditRoute
  '/categories': typeof AppCategoriesRoute
  '/settings': typeof AppSettingsRoute
  '/vat': typeof AppVatRoute
  '/': typeof AppIndexRoute
  '/clients/$id': typeof AppClientsIdRoute
  '/core-members/$id': typeof AppCoreMembersIdRoute
  '/employees/$id': typeof AppEmployeesIdRoute
  '/projects/$id': typeof AppProjectsIdRoute
  '/stand-ups/$id': typeof AppStandUpsIdRoute
  '/clients': typeof AppClientsIndexRoute
  '/core-members': typeof AppCoreMembersIndexRoute
  '/employees': typeof AppEmployeesIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/stand-ups': typeof AppStandUpsIndexRoute
  '/clients/$id/edit': typeof AppClientsIdEditRoute
  '/core-members/$id/edit': typeof AppCoreMembersIdEditRoute
  '/employees/$id/edit': typeof AppEmployeesIdEditRoute
  '/projects/$id/edit': typeof AppProjectsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/vat': typeof AppVatRoute
  '/_app/': typeof AppIndexRoute
  '/_app/clients/$id': typeof AppClientsIdRoute
  '/_app/core-members/$id': typeof AppCoreMembersIdRoute
  '/_app/employees/$id': typeof AppEmployeesIdRoute
  '/_app/projects/$id': typeof AppProjectsIdRoute
  '/_app/stand-ups/$id': typeof AppStandUpsIdRoute
  '/_app/clients/': typeof AppClientsIndexRoute
  '/_app/core-members/': typeof AppCoreMembersIndexRoute
  '/_app/employees/': typeof AppEmployeesIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/stand-ups/': typeof AppStandUpsIndexRoute
  '/_app/clients/$id_/edit': typeof AppClientsIdEditRoute
  '/_app/core-members/$id_/edit': typeof AppCoreMembersIdEditRoute
  '/_app/employees/$id_/edit': typeof AppEmployeesIdEditRoute
  '/_app/projects/$id_/edit': typeof AppProjectsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit'
    | '/categories'
    | '/settings'
    | '/vat'
    | '/clients/$id'
    | '/core-members/$id'
    | '/employees/$id'
    | '/projects/$id'
    | '/stand-ups/$id'
    | '/clients/'
    | '/core-members/'
    | '/employees/'
    | '/projects/'
    | '/stand-ups/'
    | '/clients/$id/edit'
    | '/core-members/$id/edit'
    | '/employees/$id/edit'
    | '/projects/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/audit'
    | '/categories'
    | '/settings'
    | '/vat'
    | '/'
    | '/clients/$id'
    | '/core-members/$id'
    | '/employees/$id'
    | '/projects/$id'
    | '/stand-ups/$id'
    | '/clients'
    | '/core-members'
    | '/employees'
    | '/projects'
    | '/stand-ups'
    | '/clients/$id/edit'
    | '/core-members/$id/edit'
    | '/employees/$id/edit'
    | '/projects/$id/edit'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/audit'
    | '/_app/categories'
    | '/_app/settings'
    | '/_app/vat'
    | '/_app/'
    | '/_app/clients/$id'
    | '/_app/core-members/$id'
    | '/_app/employees/$id'
    | '/_app/projects/$id'
    | '/_app/stand-ups/$id'
    | '/_app/clients/'
    | '/_app/core-members/'
    | '/_app/employees/'
    | '/_app/projects/'
    | '/_app/stand-ups/'
    | '/_app/clients/$id_/edit'
    | '/_app/core-members/$id_/edit'
    | '/_app/employees/$id_/edit'
    | '/_app/projects/$id_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vat': {
      id: '/_app/vat'
      path: '/vat'
      fullPath: '/vat'
      preLoaderRoute: typeof AppVatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stand-ups/': {
      id: '/_app/stand-ups/'
      path: '/stand-ups'
      fullPath: '/stand-ups/'
      preLoaderRoute: typeof AppStandUpsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/': {
      id: '/_app/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof AppEmployeesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/core-members/': {
      id: '/_app/core-members/'
      path: '/core-members'
      fullPath: '/core-members/'
      preLoaderRoute: typeof AppCoreMembersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/': {
      id: '/_app/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stand-ups/$id': {
      id: '/_app/stand-ups/$id'
      path: '/stand-ups/$id'
      fullPath: '/stand-ups/$id'
      preLoaderRoute: typeof AppStandUpsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$id': {
      id: '/_app/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AppProjectsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/$id': {
      id: '/_app/employees/$id'
      path: '/employees/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof AppEmployeesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/core-members/$id': {
      id: '/_app/core-members/$id'
      path: '/core-members/$id'
      fullPath: '/core-members/$id'
      preLoaderRoute: typeof AppCoreMembersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/$id': {
      id: '/_app/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AppClientsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$id_/edit': {
      id: '/_app/projects/$id_/edit'
      path: '/projects/$id/edit'
      fullPath: '/projects/$id/edit'
      preLoaderRoute: typeof AppProjectsIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/$id_/edit': {
      id: '/_app/employees/$id_/edit'
      path: '/employees/$id/edit'
      fullPath: '/employees/$id/edit'
      preLoaderRoute: typeof AppEmployeesIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/core-members/$id_/edit': {
      id: '/_app/core-members/$id_/edit'
      path: '/core-members/$id/edit'
      fullPath: '/core-members/$id/edit'
      preLoaderRoute: typeof AppCoreMembersIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/$id_/edit': {
      id: '/_app/clients/$id_/edit'
      path: '/clients/$id/edit'
      fullPath: '/clients/$id/edit'
      preLoaderRoute: typeof AppClientsIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVatRoute: typeof AppVatRoute
  AppIndexRoute: typeof AppIndexRoute
  AppClientsIdRoute: typeof AppClientsIdRoute
  AppCoreMembersIdRoute: typeof AppCoreMembersIdRoute
  AppEmployeesIdRoute: typeof AppEmployeesIdRoute
  AppProjectsIdRoute: typeof AppProjectsIdRoute
  AppStandUpsIdRoute: typeof AppStandUpsIdRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
  AppCoreMembersIndexRoute: typeof AppCoreMembersIndexRoute
  AppEmployeesIndexRoute: typeof AppEmployeesIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppStandUpsIndexRoute: typeof AppStandUpsIndexRoute
  AppClientsIdEditRoute: typeof AppClientsIdEditRoute
  AppCoreMembersIdEditRoute: typeof AppCoreMembersIdEditRoute
  AppEmployeesIdEditRoute: typeof AppEmployeesIdEditRoute
  AppProjectsIdEditRoute: typeof AppProjectsIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVatRoute: AppVatRoute,
  AppIndexRoute: AppIndexRoute,
  AppClientsIdRoute: AppClientsIdRoute,
  AppCoreMembersIdRoute: AppCoreMembersIdRoute,
  AppEmployeesIdRoute: AppEmployeesIdRoute,
  AppProjectsIdRoute: AppProjectsIdRoute,
  AppStandUpsIdRoute: AppStandUpsIdRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
  AppCoreMembersIndexRoute: AppCoreMembersIndexRoute,
  AppEmployeesIndexRoute: AppEmployeesIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppStandUpsIndexRoute: AppStandUpsIndexRoute,
  AppClientsIdEditRoute: AppClientsIdEditRoute,
  AppCoreMembersIdEditRoute: AppCoreMembersIdEditRoute,
  AppEmployeesIdEditRoute: AppEmployeesIdEditRoute,
  AppProjectsIdEditRoute: AppProjectsIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
